spring:
  profiles:
    active: 
    - dev

---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-eureka-client

server:
  port: 7001 #注册中心占用7001端口，冒号后面必须要有空格

eureka: 
  instance:
    hostname: eureka7001.com #冒号后面必须要有空格,eureka服务端的实例名称
  client: 
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务

---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-eureka-client

server:
  port: 7001 #注册中心占用7001端口，冒号后面必须要有空格

eureka: 
  instance:
    hostname: eureka7001.com #冒号后面必须要有空格,eureka服务端的实例名称
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务

#   请保存为UTF-8格式  